version: 2.1

jobs:
  build:
    docker:
      - image: returntocorp/sgrep:develop
    working_directory: /home/repo
    steps:
      - checkout
      - run:
          name: "Run sgrep"
          command: sgrep-lint --error --config=https://sgrep.live/c/r/r2c.python; 