version: 2.1

jobs:
  build:
    docker:
      - image: returntocorp/sgrep:develop
    working_directory: /home/repo
    steps:
      - checkout
      - run:
          name: "Run sgrep"
          # blocking (--error)
          # command: sgrep-lint --error --config=https://sgrep.live/c/r/r2c.python 1>&2; echo "done"
          # non-blocking
          command: sgrep-lint --config=https://sgrep.live/c/r/r2c.python.django 1>&2; echo "done"
